# Config
title: Danny van Kooten
email: hi@dvk.co
description:
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dannyvankooten.com" # the base hostname & protocol for your site
twitter_username: dannyvankooten
github_username:  dannyvankooten

# SEO settings
twitter:
  username: dannyvankooten
social:
  name: Danny van Kooten
  links:
    - https://twitter.com/dannyvankooten
    - https://github.com/dannyvankooten
    - https://keybase.io/dvk

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false
sass:
  style: compressed
gems:
  - jekyll-seo-tag
  - jekyll-sitemap

permalink: /:title/

exclude:
  - package.json
  - node_modules
  - gulpfile.js
  - assets/sass
  - Gemfile
  - Gemfile.lock
  - makefile
